version: '2'

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bank
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - /data/mysql
  money-transfer-app:
    image: money-transfer-image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8080:8080
    volumes:
      - /data/money-transfer-app
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=bank
      - DATABASE_PORT=3306
      
      