version: '2'

services:
  db:
    container_name: dbContainer
    image: mysql:5.7
    volumes:
    - ./data:/var/lib/mysql
    ports:
    - 3306
    environment:
     MYSQL_ROOT_PASSWORD: "root"
     MYSQL_USER: "root"
     MYSQL_PASSWORD: "root"
     MYSQL_DATABASE: "test"
  java:
    container_name: javaApplication
    image: openjdk:8
    depends_on:
    - db
    volumes:
    - ./example.java.helloworld/:/usr/src/myapp 
    working_dir: /usr/src/myapp
    command: bash -c "java -jar Main.jar"
